"""
TUTORIAL: Dataclass Basics - @dataclass Decorator with Ordering Support
========================================================================

In this tutorial, you'll learn how to use the @dataclass decorator to create
simple data-holding classes automatically. We'll explore the @dataclass(order=True)
parameter which automatically generates comparison methods like __lt__, __le__,
__gt__, and __ge__.

Why use @dataclass? Before dataclasses, you had to manually write __init__,
__repr__, __eq__, and other methods. Dataclasses generate these for you,
reducing boilerplate while keeping code readable and maintainable.

The order=True parameter is particularly useful when you need to sort instances
or compare them using <, <=, >, >= operators. Without it, you'd get a TypeError
when trying to compare instances.
"""

from dataclasses import dataclass


# ============ Example 1: Basic Dataclass with Ordering ============
print("=" * 70)
print("EXAMPLE 1: Creating a Card dataclass with order=True")
print("=" * 70)

@dataclass(order=True)
class Card:
    """A playing card with rank and suit.

    The order=True parameter tells @dataclass to generate comparison methods.
    Python will compare cards by rank first, then by suit (in the order you
    define the fields). This makes it easy to sort cards programmatically.
    """
    rank: str
    suit: str

    # Class attributes (not dataclass fields since they lack type hints)
    ranks = [str(n) for n in range(2, 10)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()


# Create some card instances
card1 = Card('2', 'spades')
card2 = Card('K', 'hearts')
card3 = Card('5', 'clubs')

print(f"\nCards created:")
print(f"  card1 = {card1}")
print(f"  card2 = {card2}")
print(f"  card3 = {card3}")

# Demonstrate automatic __repr__ (generated by @dataclass)
print(f"\nAutomatic __repr__ (generated by @dataclass):")
print(f"  repr(card1) = {repr(card1)}")


# ============ Example 2: Comparison Operations ============
print("\n" + "=" * 70)
print("EXAMPLE 2: Comparing cards using order=True")
print("=" * 70)

# The order=True parameter generates these comparison methods
print(f"\nComparison results (comparing cards by rank first, then suit):")
print(f"  Card('2', 'spades') < Card('K', 'hearts'): {card1 < card2}")
print(f"    WHY? '2' comes before 'K' in the ranks list")

print(f"\n  Card('5', 'clubs') > Card('2', 'spades'): {card3 > card1}")
print(f"    WHY? '5' comes after '2' in the ranks list")

# These operators would fail without order=True
print(f"\n  Card('2', 'spades') <= Card('2', 'spades'): {card1 <= Card('2', 'spades')}")
print(f"    WHY? Equality is also generated by @dataclass")


# ============ Example 3: Sorting Cards ============
print("\n" + "=" * 70)
print("EXAMPLE 3: Sorting cards using the generated comparison methods")
print("=" * 70)

cards = [
    Card('K', 'hearts'),
    Card('2', 'spades'),
    Card('5', 'clubs'),
    Card('A', 'diamonds'),
    Card('5', 'hearts'),
]

print(f"\nUnsorted cards:")
for card in cards:
    print(f"  {card}")

sorted_cards = sorted(cards)

print(f"\nSorted cards (order=True generates the comparison logic):")
for card in sorted_cards:
    print(f"  {card}")

print(f"\nWhy this order? Fields are compared left to right:")
print(f"  First by rank: 2 < 5 < 5 < A < K")
print(f"  For ties (5 = 5), then by suit: clubs < hearts")


# ============ Example 4: Class Attributes vs Instance Attributes ============
print("\n" + "=" * 70)
print("EXAMPLE 4: Understanding class vs instance attributes")
print("=" * 70)

print(f"\nClass attributes (shared across all instances):")
print(f"  Card.ranks = {Card.ranks}")
print(f"  Card.suits = {Card.suits}")

print(f"\nInstance attributes (unique to each instance):")
print(f"  card1.rank = '{card1.rank}', card1.suit = '{card1.suit}'")
print(f"  card2.rank = '{card2.rank}', card2.suit = '{card2.suit}'")

print(f"\nWhy separate them?")
print(f"  - Dataclass fields (with type hints) → instance attributes")
print(f"  - Class-level assignments without type hints → class attributes")
print(f"  - This keeps your code clear and prevents accidental mutations")


# ============ Example 5: What @dataclass(order=True) Generates ============
print("\n" + "=" * 70)
print("EXAMPLE 5: Behind the scenes - what @dataclass generates")
print("=" * 70)

print(f"\nThe @dataclass decorator automatically creates:")
print(f"  1. __init__() - initializes rank and suit from arguments")
print(f"  2. __repr__() - shows Card(rank='K', suit='hearts')")
print(f"  3. __eq__() - checks if two cards are identical")
print(f"  4. __lt__() - checks if one card < another (order=True)")
print(f"  5. __le__() - checks if one card <= another (order=True)")
print(f"  6. __gt__() - checks if one card > another (order=True)")
print(f"  7. __ge__() - checks if one card >= another (order=True)")

print(f"\nWithout @dataclass, you'd write all of this manually!")
print(f"Without order=True, comparison methods wouldn't exist.")

print(f"\n" + "=" * 70)
